//
//  Student.swift
//  On The Map
//
//  Created by Robert Barry on 3/31/16.
//  Copyright © 2016 Robert Barry. All rights reserved.
//

import Foundation

struct Student {
    
    let objectId: String! // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    let uniqueKey: String! // an extra (optional) key used to uniquely identify a StudentLocation
    let firstName: String! // the first name of the student which matches their Udacity profile first name
    let lastName: String! // the last name of the student which matches their Udacity profile last name
    let mapString: String! // the location string used for geocoding the student location
    let mediaURL: String! // the URL provided by the student
    let latitude: Float! // the latitude of the student location (ranges from -90 to 90)
    let longitude: Float! // the longitude of the student location (ranges from -180 to 180)
    
}
